# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: discord-template-notifier
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: discord-template-notifier-secret
    template:
      engineVersion: v2
      data:
        config.toml: "{{ .CONFIG_TOML }}"
  dataFrom:
    - extract:
        key: discord-template-notifier
