apiVersion: v1
kind: Secret
metadata:
    name: discord-template-notifier-secret
stringData:
    config.toml: ENC[AES256_GCM,data:7u+OW1J8gLRyEgTSRAzqwWZF105An2LLUyibg+LB6BBTpWN+I4r3X55psIzfWdrTDA7iP1LE/yy2dDK7FN/a/uaxyb6MpBTWJS2TH3/63ExPCnTJRXO0wzweGp/gnRMFKIhoiXRZPhLw6FqmheYNBbnCb86IRRUBSqJWCKHFivblyKUf/Ptc/aBca/gbSpuWToCvqDNpbXJigB29/p0uwpIs/sV55MuzKUxEhYaeCs1091bY9+0Smc8L5Nb0xw2Wh5xeB3SqUnhelIkUXAl+M6UnTirVJemfUYmjzEm43gx1nuM0KjNeQKJObvviLVGncCC17gBigkzbW8/+jZSpGRmgpWsDNjP3DCZQIYT1dFnvmge36HbU7gx4bbWu0w+gXw==,iv:SVOrqavR8Y21W//9vvPMeMJb6sWbMM97BBBeoouDBzo=,tag:Gf2PWPHW90VEr8g0sfRwAw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p4p7e5rq80nxvp98nnmwah0rlppu9yp6xgqr5h6yer8cxrk46ass9w6yn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmSFZsQjdMV3BCd3JWcDUr
            S3dieHo1SUdwdTZITDlaalI4amszcEFIbDBnCjJsZkVhdjBuVnI4aS94TzdTTTJP
            aDgxWWUzVVd1WkcvOTRTM3VZTjZobzAKLS0tIE1DYmJrWXlISE95T2pRZVpKUU5P
            N2VFalI1R3BaNmR0RlViQUVwS2FuVnMKSJE+SQ11jjv3wWlps5N2jf2PxZYPgJzL
            A5KNWCt0TEyMB7TTfyFdizVCsZ7mIRy6u+yklYN12cvTQVvNUOo2Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-07T17:19:26Z"
    mac: ENC[AES256_GCM,data:fHjXN5qB5hGkm54LVIIE9IF2LnTJbgIWCvqRjimqMlEaSIz7weE6pvyHd64d3AeI43WD7Zp46ZbMQd2vSnMd6lNh2C3tvVDQhCSwEOkloAyUFIVkluDuqNXFnB+2jexNdYmwCz9/ZbiQJrGYpA4bsOoKlD6buYMUIKHQektutco=,iv:we7attHT3IDNMVM0IpC7yBF3YNF5yBrzlz3cqrlqTks=,tag:1Sums09bdFbV0d4jR9xvCg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
