---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: atm8
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: minecraft
      version: v4.14.0
      sourceRef:
        kind: HelmRepository
        name: itzg-minecraft
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    resources:
      requests:
        memory: 9Gi
        cpu: 2
      limits:
        memory: 9Gi
        cpu: 6
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
    livenessProbe:
      initialDelaySeconds: 30
      periodSeconds: 5
      failureThreshold: 45
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
      initialDelaySeconds: 60
      periodSeconds: 5
      failureThreshold: 45
      successThreshold: 1
      timeoutSeconds: 1
    startupProbe:
      enabled: true
      failureThreshold: 30
      periodSeconds: 10
    extraEnv:
      ENABLE_AUTOPAUSE: false
      ENABLE_AUTOSTOP: false
      DEBUG: true

    minecraftServer:
      eula: true
      version: 1.19.2
      type: "AUTO_CURSEFORGE"
      forgeVersion: "43.3.0"
      memory: 8G
      viewDistance: 30
      gameMode: survival
      maxTickTime: -1
      difficulty: normal
      pvp: true
      motd: "Welcome to All the Mods 8!"
      woldSaveName: atm8
      autoCurseForge:
        apiKey:
          existingSecret: curseforge-secret
          secretKey: CF_API_KEY
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-8"
      serviceType: LoadBalancer
      servicePort: 25565
      loadBalancerIP: 10.1.0.102
    # service:
    #   main:
    #     type: LoadBalancer
    #     annotations:
    #       io.cilium/lb-ipam-ips: 10.1.0.102
    #     ports:
    #       http:
    #         enabled: false
    #       minecraft:
    #         enabled: true
    #         primary: true
    #         port: 25565
    #         protocol: TCP
    #         name: minecraft
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.parsec.sh
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "{{ .Release.Name }}.parsec.sh"
            paths:
              - path: /
                service:
                  name: main
                  port: 25565
        tls:
          - hosts:
              - *host
    persistence:
      dataDir:
        enabled: true
        existingClaim: atm8-data
        readOnly: false
        globalMounts:
          - path: /data
