---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: atm8
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: minecraft
      version: v4.14.0
      sourceRef:
        kind: HelmRepository
        name: itzg-minecraft
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: storage
  values:
    resources:
      requests:
        memory: 8Gi
        cpu: 2

    minecraftServer:
      eula: true
      version: 1.19.2
      type: "FORGE"
      forgeVersion: "43.3.0"
      memory: 8G
      viewDistance: 30
      gameMode: survival
      difficulty: normal
      pvp: true
      motd: "Welcome to All the Mods 8!"
      woldSaveName: atm8
      autoCurseForge:
        apiKey:
          existingSecret: curseforge-api-key
          secretKey: CF_API_KEY
        pageUrl: "https://www.curseforge.com/minecraft/modpacks/all-the-mods-8"
    service:
      main:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: 10.1.0.102
        ports:
          http:
            enabled: false
          minecraft:
            enabled: true
            port: 25565
            protocol: TCP
            name: minecraft
    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.parsec.sh
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
        hosts:
          - host: &host "{{ .Release.Name }}.parsec.sh"
            paths:
              - path: /
                service:
                  name: main
                  port: 25565
        tls:
          - hosts:
              - *host
    persistence:
      data:
        existingClaim: atm8-data
        readOnly: false
