ansible_become_pass: ENC[AES256_GCM,data:QSV0BS8/282rDlg=,iv:AR6xupmSGYAxYzYlwzc0PvhHPyiuWiU6VJBytNYpm5Q=,tag:0MPR73roUyUhPP/A8S/4YQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p4p7e5rq80nxvp98nnmwah0rlppu9yp6xgqr5h6yer8cxrk46ass9w6yn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPRlJBNDAvQkVNNTM5NHQ3
            alV3SlhldElUSytsZ29sL2tUdkFRc2toMEFVCkNCY25ZdEsxZkZOQThYN0xzTnUy
            WlVaL1pZbVFiQVplb2p6aTNZSThlRTQKLS0tIGhEeFFDMEVVaWxSNGI2SEQvRkFD
            YitzamFwNTJocGdtNFUxNjVhUjA5TWcKxYiMeX3J6DmBuaP9jAnoXWQBkXsInFGr
            nOHPJIUPk3rYhLUFSIzuafGH/ac6GkYDlxzLAA7J8CHf8RC0wnwA7w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-08T20:42:59Z"
    mac: ENC[AES256_GCM,data:dnIoyamO4FLL/IzPA7CWmfmATJf4+0GVy+QIE3UHNpSAqTT7zgEuHwD8fKl5BNG+ybMyFIUC6ycALQrNVCssFN5qTk6CJiycxc3euNH+7ikhacq+g8aZ/rU7keAvuJlofXcbJQquDCUdSQ6BtQsL8wZjS3aySjPR28gv9oMIeyI=,iv:76+L6IXPsQKF7L4QZ7HPgO+DqgTyZz1CPDBO6HCFpuY=,tag:ZA+L9OeTzkW1A+MEI37RjQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
