apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:WPZ94CBzEHuUkcefUtLRLRTt03Epkif7,iv:8cH0HVjhdeQM/NOJ50++W1d7VJHfS6q7RFyEBncT9Tg=,tag:CwUa57zfzZ24mbMedNWLNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p4p7e5rq80nxvp98nnmwah0rlppu9yp6xgqr5h6yer8cxrk46ass9w6yn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4YUFZOG42U2ttdUVxbVdy
            VEgzdWhjMlJjVnpESUprVXc1QkVFQlN0VHhVCi9kamE1Z09GZFh1aVJUUUNUcG1L
            Q001ZzhRS2k0dm9qNndzSDk0UUpyWUUKLS0tIGM0Qkk1OXZONStUZjM1ODBiT3NN
            N1hZaWZMWTc0ZFpUaFlQR2diRmQ2Vk0K0z3wcn5pN011vqNrfG3kTC+AnicR0Ye8
            zcZIMrtv18QupCKn3ZSzfHP1qcMpVKCFmLe6g8NKBtQb8KMMmZJXUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-08T20:43:25Z"
    mac: ENC[AES256_GCM,data:D78WlPOVXKdjUnQC9mY4zXvhPwFqB3dabjQYwW8jyVncH8bmECNH0+7LjnddZfxs5wiR6TRROGU1TPgnV8+NNIS0CiSLn5PkloPGb00c1D2kO5lKvG2i+TNiFsyWxYJyFX+4eqNfh/McyMX5ymoEm9jiwdGn9HZ6zPJj8WxOZa8=,iv:rTQu3c+dUUJiR6sHuZiZo8r2j74YVmWmXeRh2vJL7YQ=,tag:ktvOsFxVBQULcfWLRL/3gQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
