apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Cbgo+zZKg7WyEXaNAhZBbwNWGOiSJfTte7zu3Cr/OL8fmlwP8PTF2A==,iv:dUauEGF6mZIyd/wWylUP7mjXgn1O4+VJuzvEdhZAG7A=,tag:GUZxgjM2ggC5XiuFdd4IvA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p4p7e5rq80nxvp98nnmwah0rlppu9yp6xgqr5h6yer8cxrk46ass9w6yn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONzk0cTl1RlY0TXRtNDBW
            NUJPc2J6SXBkYlJRMmVPWXFZWEhQK1lwLzJrClRRd0hqNlVhSFpLWnU1TUxHdFlS
            bFp2azBVTFhCdVpCSWlMQ0h6V1BRU0EKLS0tIGVTUEVOdFNCYmR4aW5xanc2OU1u
            b0RESXJBZy9SbFpyNDRHb3Njbk12ZTQKyz8MJGCMD3Pm1Za+nmz0jwjcigosjXNG
            FCpxDVH7vo+I6dpp6xt/7x03Fbhp39B4yEtpWVY1XHHRKS0DpsG8YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-08T20:43:25Z"
    mac: ENC[AES256_GCM,data:W60u8YLLY7kk6op52YKfGKSrrmIStCUzMrVM3w1dfFPhRqvWehkK4hp2hUSA7QVQ0ef9DULJrMgWNwOsfmQ42TOrcbMsOjS6RjZBrn3UUA/FUUD2L1s1QEfm98ZThjVnJmyDNVHBXXZhkjxsiEgEwjeQEBUISxtyRrGyeosLBkQ=,iv:2sfK+Eu4K5R48oj2rHcMYofDr3+cI+2oS8Ra4LecMQs=,tag:T+MDdWufUJ+W72shLhxfxw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
