---
originRequest:
  http2Origin: true

ingress:
  - hostname: "parsec.sh"
    service: https://external-ingress-nginx-controller.flux-system.svc.cluster.local:443
    originRequest:
      originServerName: "external.parsec.sh"
  - hostname: "*.parsec.sh"
    service: https://external-ingress-nginx-controller.flux-system.svc.cluster.local:443
    originRequest:
      originServerName: "external.parsec.sh"
  - service: http_status:404
