apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
stringData:
    password: ENC[AES256_GCM,data:NHnrj407hBvxaX3xh9XCyg4flpxfLHU+Z9eaGnl5T4A3Vk1pa3q+7qLtL7w/AiPfSsGS9gVgcW8mJDfK,iv:8UqoUG/KWDUWPE64rR7zFARuqtBDEujqqDHeApBMmuo=,tag:38HEQjpkwbZncJvgv3wWqg==,type:str]
    username: ENC[AES256_GCM,data:fkYeegA=,iv:H06JYN0XdJOcsSki00vOh/CiaNU5t31FXtsFHIgTtXk=,tag:EQnf8NrXn0XrfU15VBeMzA==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p4p7e5rq80nxvp98nnmwah0rlppu9yp6xgqr5h6yer8cxrk46ass9w6yn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1N2UyWVd0ZGdMVjhzSUo0
            Qld4SncyTjRaaW1sSDNvY3lSUVhHS1RlWmtZCldTZUFhdHNiSlBKcGRaYlJ3RUx6
            enlhK011SHljZWxiM3lXVjBnUXFlZmMKLS0tIG1PYzJoc1ZqYThoNks1NnRWc0FV
            OFN2N0tDRjNhRGpuZ0M1ZEs0cDhlRVEKj0/I3XIxNrQT+YUKF0f5QkJ1vl9QQHkQ
            Ucp+k3+Ebg8mTi8VQZ2ZC7kG1culoCfeF1S7J1XzanxDpfhK3otwCw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-08T20:43:31Z"
    mac: ENC[AES256_GCM,data:mrUMDBpVEkk7ybhPUm+/pFcGHZXNLTqnfGTou79bxNSuXqFGQ4jrSG84amgYhcnmoS8RdwxfnBQB347Yo6ccCaTZNkaDAJEdR2evXvsvTsdokCIdehQXcTOKVZrxCKPV9TFN/T3WW7z8enOjnZyQOFuN+LVpdsSv4xysKyvU5X0=,iv:5UA/aSOrACta2GzEXhKdj54YJwNLWuJ180fDe7hb/sI=,tag:eCaXSAlJVbrdU2fpvWRAiA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
