---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: atm9
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: atm9-secret
    template:
      engineVersion: v2
      data:
        CF_API_KEY: "{{ .CF_API_KEY }}"
        MC_RCON_PASSWORD: "{{ .MC_RCON_PASSWORD }}"
        RCLONE_CONFIG_ZODIARK_TYPE: "ftp"
        RCLONE_CONFIG_ZODIARK_USER: "{{ .RCLONE_CONFIG_ZODIARK_USER }}"
        RCLONE_CONFIG_ZODIARK_PASS: "{{ .RCLONE_CONFIG_ZODIARK_PASS }}"
        RCLONE_CONFIG_ZODIARK_HOST: "{{ .RCLONE_CONFIG_ZODIARK_HOST }}"
  dataFrom:
    - extract:
        key: curseforge
    - extract:
        key: minecraft
    - extract:
        key: ftp
