apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:fZG50+BzzgPDGYW5BQfY9KHErDOZ+d7vX2WujMi7yMn+4SYzbabgvA==,iv:uyFYjCH0006oVECSegONRtiKLK/St3v/ylkpQUxQw5A=,tag:TfmVQLZn0AxNuYiwu7PHgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p4p7e5rq80nxvp98nnmwah0rlppu9yp6xgqr5h6yer8cxrk46ass9w6yn7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMXZsSGxyb01WVjRWYll1
            VVp1QzFiL2l3YkFUVVZ5djZTcG9QdmlLUm44ClN5K29HdlNaWmUzRmZiZDMvdDlp
            UmNrTzV1cU52RCtZM20vMGN5eFFMaDAKLS0tIE9Wc3pSa0s3aEtGK0V5RFROZDNh
            L1Rzcmg1VFcxMnBYQjNtVGdldnBmZGsK1RMfm22OOBFh2JZOWKyJWy5uXbQ9Gg55
            /Qxgt+hIh0hgRvFhldCIy7LNp19DN9cg03ibdBFzKeVvvJORijHayg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-08T20:43:25Z"
    mac: ENC[AES256_GCM,data:3ebHqPa7Hc3IhDVABuF6qKzeSsZs0xI0Zof69WnVRsLuEtM042O0HcoZdkKC4hCWtTlKUbgscd4raoNSPmviUN/2oPmHssz7vongqmM4denOotiEhBnfH6/m2P4OKwbw0wmrQSFKxRz6RjUNNKM/ahM8ZxnU6GKJEh0bSSVYqSs=,iv:8pqyKRCO3GS9WZlIcMv3RnT/coUkV6/mfNF8vve4iPU=,tag:fDe8Xln0lJTsEUeEvc24oA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
