---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
components:
  - ../../components/common
resources:
  - ./namespace.yaml
  - ./internal/ks.yaml
  - ./external/ks.yaml
  - ./echo-server/ks.yaml
